### ISSUE TITLE
No version in public app

### ISSUE THREAD

**Issue by YesThatAllen** [zendesklabs/url_builder_app#22]
I just switched back to the public app, so i could get auto-updates, I hope

I'm seeing this:

```
Location: Ticket, New Ticket 
Unknown Version - Last updated 165 days ago
```

Could we get an update to ensure we can see a version, #21 and maybe #20 too?

**Comment by rosendin** [comment]
Fixed in https://github.com/zendesklabs/url_builder_app/commit/ac72567f4dd8e28cb747a4e4540bfd1e54a9e5f1
