### ISSUE TITLE
Not processing liquid in the title?

### ISSUE THREAD

**Issue by YesThatAllen** [zendesklabs/url_builder_app#6]
The following in json is working to create the URLs I need, but the Title isn't being processed:

```json
[
  {
    "title": "{{ticket.organization.organization_fields.subdomain}}",
    "url": "https://{{ticket.organization.organization_fields.subdomain}}.ourdomain.com/"
  },
  {
    "title": "Admin Page",
    "url": "https://admin.ourdomain.com/{{ticket.organization.organization_fields.subdomain}}"
  }
]
```

I would expect the title to be processed as well. Should it?

![snapndrag_504](https://cloud.githubusercontent.com/assets/2879972/5160716/0aec523a-735a-11e4-8bca-f68bc7b8fe1e.png)

**Comment by jham1** [comment]
I think it's also key for the app to handle filters in liquid. For example,

```{{'18886665555' | remove:'+' | remove_first: '1'}}```

...should output 8886665555 (currently filters prevent the liquid from passing in at all, unless I'm doing something incorrectly). Key for me to be able to remove the country code and any additional characters that exist as phone number prefixes.

If anyone has thoughts on how to get this app to process liquid filters any insight would be much appreciated.

**Comment by YesThatAllen** [comment]
Is there a sense of whether this is possible?
